FROM python:3.8.5-alpine

#set work directory
WORKDIR /usr/src

COPY . .

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update && apk add \
    postgresql-dev \
    gcc \
    python3-dev \
    musl-dev

# install dependencies
RUN pip3 install --upgrade pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN pip3 install gunicorn

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]