version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db
#    volumes:
#      - postgres_data:var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    restart: always
    build:
      context: ""
      dockerfile: DockerFile
    container_name: web
    volumes:
      - /web:usr/src/
    ports:
      - "8000:8000"
    env_file:
      - .env
#
#  volumes:
#    postgres_data:
#      - postgres_data
#    web: